Repository AY2122S1-CS2103T-T13-1/tp, pull requests merged in 2021-10, with the labels that each got.

#58 Change UI
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/module/lesson/LessonTest.java
Labels: hacktoberfest-accepted

#60 Add ModBook class and storage classes for modules and ModBook
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/ModBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyModBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/UniqueModuleList.java
  src/main/java/seedu/address/model/module/exceptions/DuplicateModuleException.java
  src/main/java/seedu/address/model/module/exceptions/ModuleNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedModule.java
  src/main/java/seedu/address/storage/JsonModBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableModBook.java
  src/main/java/seedu/address/storage/ModBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonModBookStorageTest/invalidAndValidModuleModBook.json
  src/test/data/JsonModBookStorageTest/invalidModuleModBook.json
  src/test/data/JsonModBookStorageTest/notJsonFormatModBook.json
  src/test/data/JsonSerializableModBookTest/duplicateModuleModBook.json
  src/test/data/JsonSerializableModBookTest/invalidModuleModBook.json
  src/test/data/JsonSerializableModBookTest/typicalModulesModBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/module/ModuleTest.java
  src/test/java/seedu/address/storage/JsonAdaptedLessonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedModuleTest.java
  src/test/java/seedu/address/storage/JsonModBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableModBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalModules.java
  src/test/java/seedu/address/testutil/builders/ModBookBuilder.java
  src/test/java/seedu/address/testutil/builders/ModuleBuilder.java
Labels: hacktoberfest-accepted

#61 GUI Update
  copyright.txt
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/main/java/seedu/address/model/module/exam/Exam.java
  src/main/java/seedu/address/model/module/lesson/Lesson.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/ModBook.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/commons/util/AppUtilTest.java
Labels: hacktoberfest-accepted

#68 Polish GUI
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/State.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ModuleDetailCard.java
  src/main/java/seedu/address/ui/ModuleExamsCard.java
  src/main/java/seedu/address/ui/ModuleLessonsCard.java
  src/main/java/seedu/address/ui/ModuleListPanel.java
  src/main/java/seedu/address/ui/ModuleSummaryCard.java
  src/main/resources/view/ModuleDetailCard.fxml
  src/main/resources/view/ModuleExamsCard.fxml
  src/main/resources/view/ModuleLessonsCard.fxml
  src/main/resources/view/ModuleSummaryCard.fxml
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: hacktoberfest-accepted

#69 Add Detail Command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DetailCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DetailCommandParser.java
  src/main/java/seedu/address/model/module/predicates/HasModuleCodePredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DetailCommandTest.java
  src/test/java/seedu/address/logic/parser/DetailCommandParserTest.java
  src/test/java/seedu/address/model/module/predicates/HasModuleCodePredicateTest.java
Labels: type.Task, hacktoberfest-accepted

#70 Pass GuiState from MainWindow to Parser
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/DetailCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/GuiState.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/DetailCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/Parser.java
  src/main/java/seedu/address/logic/parser/exceptions/GuiStateException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandResultTest.java
  src/test/java/seedu/address/logic/commands/DetailCommandTest.java
  src/test/java/seedu/address/logic/commands/ExitCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/DetailCommandParserTest.java
Labels: hacktoberfest-accepted

#76 fix parseFirstArgs
  src/main/java/seedu/address/logic/parser/ParserUtil.java
Labels: hacktoberfest-accepted

#101 Add edit commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/delete/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/delete/DeleteLessonCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditExamCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditLessonCommand.java
  src/main/java/seedu/address/logic/commands/edit/EditModCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/ModBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/module/Module.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/add/AddExamCommandTest.java
  src/test/java/seedu/address/logic/commands/add/AddLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/add/AddModCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditExamCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditLessonCommandTest.java
  src/test/java/seedu/address/logic/commands/edit/EditModCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Story, hacktoberfest-accepted

#115 Change archive name
  build.gradle
Labels: hacktoberfest-accepted
